"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_operation_initiator import V1alpha1OperationInitiator


class TestV1alpha1OperationInitiator(unittest.TestCase):
    """V1alpha1OperationInitiator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1OperationInitiator(self):
        """Test V1alpha1OperationInitiator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1OperationInitiator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
