"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import unittest

import argocd_python_client
from argocd_python_client.api.version_service_api import VersionServiceApi  # noqa: E501


class TestVersionServiceApi(unittest.TestCase):
    """VersionServiceApi unit test stubs"""

    def setUp(self):
        self.api = VersionServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_version_service_version(self):
        """Test case for version_service_version

        Version returns version information of the API server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
