"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.applicationv1alpha1_env_entry import Applicationv1alpha1EnvEntry


class TestApplicationv1alpha1EnvEntry(unittest.TestCase):
    """Applicationv1alpha1EnvEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationv1alpha1EnvEntry(self):
        """Test Applicationv1alpha1EnvEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Applicationv1alpha1EnvEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
