"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.account_create_token_response import AccountCreateTokenResponse


class TestAccountCreateTokenResponse(unittest.TestCase):
    """AccountCreateTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountCreateTokenResponse(self):
        """Test AccountCreateTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountCreateTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
