"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_micro_time import V1MicroTime


class TestV1MicroTime(unittest.TestCase):
    """V1MicroTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MicroTime(self):
        """Test V1MicroTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1MicroTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
