"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.version_version_message import VersionVersionMessage


class TestVersionVersionMessage(unittest.TestCase):
    """VersionVersionMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionVersionMessage(self):
        """Test VersionVersionMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionVersionMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
