"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_sync_operation_resource import V1alpha1SyncOperationResource


class TestV1alpha1SyncOperationResource(unittest.TestCase):
    """V1alpha1SyncOperationResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncOperationResource(self):
        """Test V1alpha1SyncOperationResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1SyncOperationResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
