"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.account_can_i_response import AccountCanIResponse


class TestAccountCanIResponse(unittest.TestCase):
    """AccountCanIResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountCanIResponse(self):
        """Test AccountCanIResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountCanIResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
