"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_list_meta import V1ListMeta
from argocd_python_client.model.v1alpha1_gnu_pg_public_key import V1alpha1GnuPGPublicKey
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1GnuPGPublicKey'] = V1alpha1GnuPGPublicKey
from argocd_python_client.model.v1alpha1_gnu_pg_public_key_list import V1alpha1GnuPGPublicKeyList


class TestV1alpha1GnuPGPublicKeyList(unittest.TestCase):
    """V1alpha1GnuPGPublicKeyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1GnuPGPublicKeyList(self):
        """Test V1alpha1GnuPGPublicKeyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1GnuPGPublicKeyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
