"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_gnu_pg_public_key_list import V1alpha1GnuPGPublicKeyList
globals()['V1alpha1GnuPGPublicKeyList'] = V1alpha1GnuPGPublicKeyList
from openapi_client.model.gpgkey_gnu_pg_public_key_create_response import GpgkeyGnuPGPublicKeyCreateResponse


class TestGpgkeyGnuPGPublicKeyCreateResponse(unittest.TestCase):
    """GpgkeyGnuPGPublicKeyCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGpgkeyGnuPGPublicKeyCreateResponse(self):
        """Test GpgkeyGnuPGPublicKeyCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GpgkeyGnuPGPublicKeyCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
