"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_token import AccountToken


class TestAccountToken(unittest.TestCase):
    """AccountToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountToken(self):
        """Test AccountToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
