"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_application_source_directory import V1alpha1ApplicationSourceDirectory
from argocd_python_client.model.v1alpha1_application_source_helm import V1alpha1ApplicationSourceHelm
from argocd_python_client.model.v1alpha1_application_source_ksonnet import V1alpha1ApplicationSourceKsonnet
from argocd_python_client.model.v1alpha1_application_source_kustomize import V1alpha1ApplicationSourceKustomize
from argocd_python_client.model.v1alpha1_application_source_plugin import V1alpha1ApplicationSourcePlugin
globals()['V1alpha1ApplicationSourceDirectory'] = V1alpha1ApplicationSourceDirectory
globals()['V1alpha1ApplicationSourceHelm'] = V1alpha1ApplicationSourceHelm
globals()['V1alpha1ApplicationSourceKsonnet'] = V1alpha1ApplicationSourceKsonnet
globals()['V1alpha1ApplicationSourceKustomize'] = V1alpha1ApplicationSourceKustomize
globals()['V1alpha1ApplicationSourcePlugin'] = V1alpha1ApplicationSourcePlugin
from argocd_python_client.model.v1alpha1_application_source import V1alpha1ApplicationSource


class TestV1alpha1ApplicationSource(unittest.TestCase):
    """V1alpha1ApplicationSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSource(self):
        """Test V1alpha1ApplicationSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
