"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_backoff import V1alpha1Backoff
globals()['V1alpha1Backoff'] = V1alpha1Backoff
from argocd_python_client.model.v1alpha1_retry_strategy import V1alpha1RetryStrategy


class TestV1alpha1RetryStrategy(unittest.TestCase):
    """V1alpha1RetryStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RetryStrategy(self):
        """Test V1alpha1RetryStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1RetryStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
