"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_list_meta import V1ListMeta
from argocd_python_client.model.v1alpha1_cluster import V1alpha1Cluster
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1Cluster'] = V1alpha1Cluster
from argocd_python_client.model.v1alpha1_cluster_list import V1alpha1ClusterList


class TestV1alpha1ClusterList(unittest.TestCase):
    """V1alpha1ClusterList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ClusterList(self):
        """Test V1alpha1ClusterList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ClusterList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
