"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.repository_app_info import RepositoryAppInfo
globals()['RepositoryAppInfo'] = RepositoryAppInfo
from argocd_python_client.model.repository_repo_apps_response import RepositoryRepoAppsResponse


class TestRepositoryRepoAppsResponse(unittest.TestCase):
    """RepositoryRepoAppsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRepoAppsResponse(self):
        """Test RepositoryRepoAppsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryRepoAppsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
