"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cluster_connector import ClusterConnector


class TestClusterConnector(unittest.TestCase):
    """ClusterConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterConnector(self):
        """Test ClusterConnector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterConnector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
