"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.application_sync_options import ApplicationSyncOptions


class TestApplicationSyncOptions(unittest.TestCase):
    """ApplicationSyncOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationSyncOptions(self):
        """Test ApplicationSyncOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationSyncOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
