"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_resource_action_param import V1alpha1ResourceActionParam
globals()['V1alpha1ResourceActionParam'] = V1alpha1ResourceActionParam
from openapi_client.model.v1alpha1_resource_action import V1alpha1ResourceAction


class TestV1alpha1ResourceAction(unittest.TestCase):
    """V1alpha1ResourceAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceAction(self):
        """Test V1alpha1ResourceAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
