"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_sync_window import V1alpha1SyncWindow
globals()['V1alpha1SyncWindow'] = V1alpha1SyncWindow
from argocd_python_client.model.project_sync_windows_response import ProjectSyncWindowsResponse


class TestProjectSyncWindowsResponse(unittest.TestCase):
    """ProjectSyncWindowsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectSyncWindowsResponse(self):
        """Test ProjectSyncWindowsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectSyncWindowsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
