"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_port_status import V1PortStatus


class TestV1PortStatus(unittest.TestCase):
    """V1PortStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PortStatus(self):
        """Test V1PortStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1PortStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
