"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.repository_ksonnet_environment import RepositoryKsonnetEnvironment
from argocd_python_client.model.v1alpha1_ksonnet_parameter import V1alpha1KsonnetParameter
globals()['RepositoryKsonnetEnvironment'] = RepositoryKsonnetEnvironment
globals()['V1alpha1KsonnetParameter'] = V1alpha1KsonnetParameter
from argocd_python_client.model.repository_ksonnet_app_spec import RepositoryKsonnetAppSpec


class TestRepositoryKsonnetAppSpec(unittest.TestCase):
    """RepositoryKsonnetAppSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryKsonnetAppSpec(self):
        """Test RepositoryKsonnetAppSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryKsonnetAppSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
