"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.application_sync_options import ApplicationSyncOptions
from argocd_python_client.model.v1alpha1_info import V1alpha1Info
from argocd_python_client.model.v1alpha1_retry_strategy import V1alpha1RetryStrategy
from argocd_python_client.model.v1alpha1_sync_operation_resource import V1alpha1SyncOperationResource
from argocd_python_client.model.v1alpha1_sync_strategy import V1alpha1SyncStrategy
globals()['ApplicationSyncOptions'] = ApplicationSyncOptions
globals()['V1alpha1Info'] = V1alpha1Info
globals()['V1alpha1RetryStrategy'] = V1alpha1RetryStrategy
globals()['V1alpha1SyncOperationResource'] = V1alpha1SyncOperationResource
globals()['V1alpha1SyncStrategy'] = V1alpha1SyncStrategy
from argocd_python_client.model.application_application_sync_request import ApplicationApplicationSyncRequest


class TestApplicationApplicationSyncRequest(unittest.TestCase):
    """ApplicationApplicationSyncRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationApplicationSyncRequest(self):
        """Test ApplicationApplicationSyncRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationApplicationSyncRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
