"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_time import V1Time
globals()['V1Time'] = V1Time
from argocd_python_client.model.v1alpha1_revision_metadata import V1alpha1RevisionMetadata


class TestV1alpha1RevisionMetadata(unittest.TestCase):
    """V1alpha1RevisionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RevisionMetadata(self):
        """Test V1alpha1RevisionMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1RevisionMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
