"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_helm_file_parameter import V1alpha1HelmFileParameter


class TestV1alpha1HelmFileParameter(unittest.TestCase):
    """V1alpha1HelmFileParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1HelmFileParameter(self):
        """Test V1alpha1HelmFileParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1HelmFileParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
