"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.repository_helm_app_spec import RepositoryHelmAppSpec
from argocd_python_client.model.repository_ksonnet_app_spec import RepositoryKsonnetAppSpec
from argocd_python_client.model.repository_kustomize_app_spec import RepositoryKustomizeAppSpec
globals()['RepositoryHelmAppSpec'] = RepositoryHelmAppSpec
globals()['RepositoryKsonnetAppSpec'] = RepositoryKsonnetAppSpec
globals()['RepositoryKustomizeAppSpec'] = RepositoryKustomizeAppSpec
from argocd_python_client.model.repository_repo_app_details_response import RepositoryRepoAppDetailsResponse


class TestRepositoryRepoAppDetailsResponse(unittest.TestCase):
    """RepositoryRepoAppDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRepoAppDetailsResponse(self):
        """Test RepositoryRepoAppDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryRepoAppDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
