"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_time import V1Time


class TestV1Time(unittest.TestCase):
    """V1Time unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1Time(self):
        """Test V1Time"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1Time()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
