"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_sync_strategy_apply import V1alpha1SyncStrategyApply
from openapi_client.model.v1alpha1_sync_strategy_hook import V1alpha1SyncStrategyHook
globals()['V1alpha1SyncStrategyApply'] = V1alpha1SyncStrategyApply
globals()['V1alpha1SyncStrategyHook'] = V1alpha1SyncStrategyHook
from openapi_client.model.v1alpha1_sync_strategy import V1alpha1SyncStrategy


class TestV1alpha1SyncStrategy(unittest.TestCase):
    """V1alpha1SyncStrategy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncStrategy(self):
        """Test V1alpha1SyncStrategy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1SyncStrategy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
