"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_event_source import V1EventSource


class TestV1EventSource(unittest.TestCase):
    """V1EventSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1EventSource(self):
        """Test V1EventSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1EventSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
