"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.repository_ksonnet_environment_destination import RepositoryKsonnetEnvironmentDestination
globals()['RepositoryKsonnetEnvironmentDestination'] = RepositoryKsonnetEnvironmentDestination
from openapi_client.model.repository_ksonnet_environment import RepositoryKsonnetEnvironment


class TestRepositoryKsonnetEnvironment(unittest.TestCase):
    """RepositoryKsonnetEnvironment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryKsonnetEnvironment(self):
        """Test RepositoryKsonnetEnvironment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryKsonnetEnvironment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
