"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_aws_auth_config import V1alpha1AWSAuthConfig
from openapi_client.model.v1alpha1_exec_provider_config import V1alpha1ExecProviderConfig
from openapi_client.model.v1alpha1_tls_client_config import V1alpha1TLSClientConfig
globals()['V1alpha1AWSAuthConfig'] = V1alpha1AWSAuthConfig
globals()['V1alpha1ExecProviderConfig'] = V1alpha1ExecProviderConfig
globals()['V1alpha1TLSClientConfig'] = V1alpha1TLSClientConfig
from openapi_client.model.v1alpha1_cluster_config import V1alpha1ClusterConfig


class TestV1alpha1ClusterConfig(unittest.TestCase):
    """V1alpha1ClusterConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ClusterConfig(self):
        """Test V1alpha1ClusterConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ClusterConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
