"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.cluster_help import ClusterHelp


class TestClusterHelp(unittest.TestCase):
    """ClusterHelp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterHelp(self):
        """Test ClusterHelp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterHelp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
