"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.cluster_google_analytics_config import ClusterGoogleAnalyticsConfig


class TestClusterGoogleAnalyticsConfig(unittest.TestCase):
    """ClusterGoogleAnalyticsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterGoogleAnalyticsConfig(self):
        """Test ClusterGoogleAnalyticsConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterGoogleAnalyticsConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
