"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_micro_time import V1MicroTime
globals()['V1MicroTime'] = V1MicroTime
from openapi_client.model.v1_event_series import V1EventSeries


class TestV1EventSeries(unittest.TestCase):
    """V1EventSeries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1EventSeries(self):
        """Test V1EventSeries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1EventSeries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
