"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.account_account import AccountAccount
globals()['AccountAccount'] = AccountAccount
from argocd_python_client.model.account_accounts_list import AccountAccountsList


class TestAccountAccountsList(unittest.TestCase):
    """AccountAccountsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountAccountsList(self):
        """Test AccountAccountsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountAccountsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
