"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.oidc_claim import OidcClaim


class TestOidcClaim(unittest.TestCase):
    """OidcClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOidcClaim(self):
        """Test OidcClaim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OidcClaim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
