"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_connection_state import V1alpha1ConnectionState
globals()['V1alpha1ConnectionState'] = V1alpha1ConnectionState
from argocd_python_client.model.v1alpha1_repository import V1alpha1Repository


class TestV1alpha1Repository(unittest.TestCase):
    """V1alpha1Repository unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1Repository(self):
        """Test V1alpha1Repository"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1Repository()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
