"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_application_source_kustomize import V1alpha1ApplicationSourceKustomize


class TestV1alpha1ApplicationSourceKustomize(unittest.TestCase):
    """V1alpha1ApplicationSourceKustomize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourceKustomize(self):
        """Test V1alpha1ApplicationSourceKustomize"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSourceKustomize()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
