"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.account_token import AccountToken
globals()['AccountToken'] = AccountToken
from argocd_python_client.model.account_account import AccountAccount


class TestAccountAccount(unittest.TestCase):
    """AccountAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountAccount(self):
        """Test AccountAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
