"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_kustomize_options import V1alpha1KustomizeOptions


class TestV1alpha1KustomizeOptions(unittest.TestCase):
    """V1alpha1KustomizeOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1KustomizeOptions(self):
        """Test V1alpha1KustomizeOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1KustomizeOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
