"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_jwt_token import V1alpha1JWTToken
globals()['V1alpha1JWTToken'] = V1alpha1JWTToken
from argocd_python_client.model.v1alpha1_jwt_tokens import V1alpha1JWTTokens


class TestV1alpha1JWTTokens(unittest.TestCase):
    """V1alpha1JWTTokens unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1JWTTokens(self):
        """Test V1alpha1JWTTokens"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1JWTTokens()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
