"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.application_application_resource_response import ApplicationApplicationResourceResponse


class TestApplicationApplicationResourceResponse(unittest.TestCase):
    """ApplicationApplicationResourceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationApplicationResourceResponse(self):
        """Test ApplicationApplicationResourceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationApplicationResourceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
