"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_application_summary import V1alpha1ApplicationSummary


class TestV1alpha1ApplicationSummary(unittest.TestCase):
    """V1alpha1ApplicationSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSummary(self):
        """Test V1alpha1ApplicationSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
