"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_group_kind import V1GroupKind
from openapi_client.model.v1alpha1_application_destination import V1alpha1ApplicationDestination
from openapi_client.model.v1alpha1_orphaned_resources_monitor_settings import V1alpha1OrphanedResourcesMonitorSettings
from openapi_client.model.v1alpha1_project_role import V1alpha1ProjectRole
from openapi_client.model.v1alpha1_signature_key import V1alpha1SignatureKey
from openapi_client.model.v1alpha1_sync_window import V1alpha1SyncWindow
globals()['V1GroupKind'] = V1GroupKind
globals()['V1alpha1ApplicationDestination'] = V1alpha1ApplicationDestination
globals()['V1alpha1OrphanedResourcesMonitorSettings'] = V1alpha1OrphanedResourcesMonitorSettings
globals()['V1alpha1ProjectRole'] = V1alpha1ProjectRole
globals()['V1alpha1SignatureKey'] = V1alpha1SignatureKey
globals()['V1alpha1SyncWindow'] = V1alpha1SyncWindow
from openapi_client.model.v1alpha1_app_project_spec import V1alpha1AppProjectSpec


class TestV1alpha1AppProjectSpec(unittest.TestCase):
    """V1alpha1AppProjectSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1AppProjectSpec(self):
        """Test V1alpha1AppProjectSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1AppProjectSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
