"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_retry_strategy import V1alpha1RetryStrategy
from openapi_client.model.v1alpha1_sync_policy_automated import V1alpha1SyncPolicyAutomated
globals()['V1alpha1RetryStrategy'] = V1alpha1RetryStrategy
globals()['V1alpha1SyncPolicyAutomated'] = V1alpha1SyncPolicyAutomated
from openapi_client.model.v1alpha1_sync_policy import V1alpha1SyncPolicy


class TestV1alpha1SyncPolicy(unittest.TestCase):
    """V1alpha1SyncPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncPolicy(self):
        """Test V1alpha1SyncPolicy"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1SyncPolicy()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
