"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_resource_action_param import V1alpha1ResourceActionParam


class TestV1alpha1ResourceActionParam(unittest.TestCase):
    """V1alpha1ResourceActionParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceActionParam(self):
        """Test V1alpha1ResourceActionParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceActionParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
