"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_jsonnet_var import V1alpha1JsonnetVar
globals()['V1alpha1JsonnetVar'] = V1alpha1JsonnetVar
from openapi_client.model.v1alpha1_application_source_jsonnet import V1alpha1ApplicationSourceJsonnet


class TestV1alpha1ApplicationSourceJsonnet(unittest.TestCase):
    """V1alpha1ApplicationSourceJsonnet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourceJsonnet(self):
        """Test V1alpha1ApplicationSourceJsonnet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSourceJsonnet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
