"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_app_project import V1alpha1AppProject
globals()['V1alpha1AppProject'] = V1alpha1AppProject
from argocd_python_client.model.project_project_create_request import ProjectProjectCreateRequest


class TestProjectProjectCreateRequest(unittest.TestCase):
    """ProjectProjectCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectCreateRequest(self):
        """Test ProjectProjectCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
