"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_time import V1Time
from argocd_python_client.model.v1alpha1_cluster_config import V1alpha1ClusterConfig
from argocd_python_client.model.v1alpha1_cluster_info import V1alpha1ClusterInfo
from argocd_python_client.model.v1alpha1_connection_state import V1alpha1ConnectionState
globals()['V1Time'] = V1Time
globals()['V1alpha1ClusterConfig'] = V1alpha1ClusterConfig
globals()['V1alpha1ClusterInfo'] = V1alpha1ClusterInfo
globals()['V1alpha1ConnectionState'] = V1alpha1ConnectionState
from argocd_python_client.model.v1alpha1_cluster import V1alpha1Cluster


class TestV1alpha1Cluster(unittest.TestCase):
    """V1alpha1Cluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1Cluster(self):
        """Test V1alpha1Cluster"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1Cluster()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
