"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.oidc_claim import OidcClaim
globals()['OidcClaim'] = OidcClaim
from argocd_python_client.model.cluster_oidc_config import ClusterOIDCConfig


class TestClusterOIDCConfig(unittest.TestCase):
    """ClusterOIDCConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterOIDCConfig(self):
        """Test ClusterOIDCConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterOIDCConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
