"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_list_meta import V1ListMeta
from openapi_client.model.v1alpha1_application import V1alpha1Application
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1Application'] = V1alpha1Application
from openapi_client.model.v1alpha1_application_list import V1alpha1ApplicationList


class TestV1alpha1ApplicationList(unittest.TestCase):
    """V1alpha1ApplicationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationList(self):
        """Test V1alpha1ApplicationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
