"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_object_meta import V1ObjectMeta
from argocd_python_client.model.v1alpha1_application_spec import V1alpha1ApplicationSpec
from argocd_python_client.model.v1alpha1_application_status import V1alpha1ApplicationStatus
from argocd_python_client.model.v1alpha1_operation import V1alpha1Operation
globals()['V1ObjectMeta'] = V1ObjectMeta
globals()['V1alpha1ApplicationSpec'] = V1alpha1ApplicationSpec
globals()['V1alpha1ApplicationStatus'] = V1alpha1ApplicationStatus
globals()['V1alpha1Operation'] = V1alpha1Operation
from argocd_python_client.model.v1alpha1_application import V1alpha1Application


class TestV1alpha1Application(unittest.TestCase):
    """V1alpha1Application unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1Application(self):
        """Test V1alpha1Application"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1Application()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
