"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_known_type_field import V1alpha1KnownTypeField
from argocd_python_client.model.v1alpha1_override_ignore_diff import V1alpha1OverrideIgnoreDiff
globals()['V1alpha1KnownTypeField'] = V1alpha1KnownTypeField
globals()['V1alpha1OverrideIgnoreDiff'] = V1alpha1OverrideIgnoreDiff
from argocd_python_client.model.v1alpha1_resource_override import V1alpha1ResourceOverride


class TestV1alpha1ResourceOverride(unittest.TestCase):
    """V1alpha1ResourceOverride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceOverride(self):
        """Test V1alpha1ResourceOverride"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceOverride()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
