"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_application_source import V1alpha1ApplicationSource
globals()['V1alpha1ApplicationSource'] = V1alpha1ApplicationSource
from openapi_client.model.repository_repo_app_details_query import RepositoryRepoAppDetailsQuery


class TestRepositoryRepoAppDetailsQuery(unittest.TestCase):
    """RepositoryRepoAppDetailsQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRepoAppDetailsQuery(self):
        """Test RepositoryRepoAppDetailsQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryRepoAppDetailsQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
