"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.protobuf_any import ProtobufAny
globals()['ProtobufAny'] = ProtobufAny
from argocd_python_client.model.runtime_error import RuntimeError


class TestRuntimeError(unittest.TestCase):
    """RuntimeError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeError(self):
        """Test RuntimeError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuntimeError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
