"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_time import V1Time
from argocd_python_client.model.v1alpha1_operation import V1alpha1Operation
from argocd_python_client.model.v1alpha1_sync_operation_result import V1alpha1SyncOperationResult
globals()['V1Time'] = V1Time
globals()['V1alpha1Operation'] = V1alpha1Operation
globals()['V1alpha1SyncOperationResult'] = V1alpha1SyncOperationResult
from argocd_python_client.model.v1alpha1_operation_state import V1alpha1OperationState


class TestV1alpha1OperationState(unittest.TestCase):
    """V1alpha1OperationState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1OperationState(self):
        """Test V1alpha1OperationState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1OperationState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
