"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_object_meta import V1ObjectMeta
from openapi_client.model.v1alpha1_app_project_spec import V1alpha1AppProjectSpec
from openapi_client.model.v1alpha1_app_project_status import V1alpha1AppProjectStatus
globals()['V1ObjectMeta'] = V1ObjectMeta
globals()['V1alpha1AppProjectSpec'] = V1alpha1AppProjectSpec
globals()['V1alpha1AppProjectStatus'] = V1alpha1AppProjectStatus
from openapi_client.model.v1alpha1_app_project import V1alpha1AppProject


class TestV1alpha1AppProject(unittest.TestCase):
    """V1alpha1AppProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1AppProject(self):
        """Test V1alpha1AppProject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1AppProject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
