"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_fields_v1 import V1FieldsV1
from argocd_python_client.model.v1_time import V1Time
globals()['V1FieldsV1'] = V1FieldsV1
globals()['V1Time'] = V1Time
from argocd_python_client.model.v1_managed_fields_entry import V1ManagedFieldsEntry


class TestV1ManagedFieldsEntry(unittest.TestCase):
    """V1ManagedFieldsEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ManagedFieldsEntry(self):
        """Test V1ManagedFieldsEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1ManagedFieldsEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
