"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_orphaned_resource_key import V1alpha1OrphanedResourceKey


class TestV1alpha1OrphanedResourceKey(unittest.TestCase):
    """V1alpha1OrphanedResourceKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1OrphanedResourceKey(self):
        """Test V1alpha1OrphanedResourceKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1OrphanedResourceKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
