"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_update_password_request import AccountUpdatePasswordRequest


class TestAccountUpdatePasswordRequest(unittest.TestCase):
    """AccountUpdatePasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountUpdatePasswordRequest(self):
        """Test AccountUpdatePasswordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountUpdatePasswordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
