"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_list_meta import V1ListMeta
from openapi_client.model.v1alpha1_repository import V1alpha1Repository
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1Repository'] = V1alpha1Repository
from openapi_client.model.v1alpha1_repository_list import V1alpha1RepositoryList


class TestV1alpha1RepositoryList(unittest.TestCase):
    """V1alpha1RepositoryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RepositoryList(self):
        """Test V1alpha1RepositoryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1RepositoryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
