"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_object_reference import V1ObjectReference


class TestV1ObjectReference(unittest.TestCase):
    """V1ObjectReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ObjectReference(self):
        """Test V1ObjectReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1ObjectReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
