"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_info import V1alpha1Info
from openapi_client.model.v1alpha1_operation_initiator import V1alpha1OperationInitiator
from openapi_client.model.v1alpha1_retry_strategy import V1alpha1RetryStrategy
from openapi_client.model.v1alpha1_sync_operation import V1alpha1SyncOperation
globals()['V1alpha1Info'] = V1alpha1Info
globals()['V1alpha1OperationInitiator'] = V1alpha1OperationInitiator
globals()['V1alpha1RetryStrategy'] = V1alpha1RetryStrategy
globals()['V1alpha1SyncOperation'] = V1alpha1SyncOperation
from openapi_client.model.v1alpha1_operation import V1alpha1Operation


class TestV1alpha1Operation(unittest.TestCase):
    """V1alpha1Operation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1Operation(self):
        """Test V1alpha1Operation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1Operation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
