"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_resource_diff import V1alpha1ResourceDiff
globals()['V1alpha1ResourceDiff'] = V1alpha1ResourceDiff
from argocd_python_client.model.application_managed_resources_response import ApplicationManagedResourcesResponse


class TestApplicationManagedResourcesResponse(unittest.TestCase):
    """ApplicationManagedResourcesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationManagedResourcesResponse(self):
        """Test ApplicationManagedResourcesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationManagedResourcesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
