"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.protobuf_any import ProtobufAny
globals()['ProtobufAny'] = ProtobufAny
from argocd_python_client.model.runtime_stream_error import RuntimeStreamError


class TestRuntimeStreamError(unittest.TestCase):
    """RuntimeStreamError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeStreamError(self):
        """Test RuntimeStreamError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuntimeStreamError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
