"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.repository_helm_chart import RepositoryHelmChart
globals()['RepositoryHelmChart'] = RepositoryHelmChart
from argocd_python_client.model.repository_helm_charts_response import RepositoryHelmChartsResponse


class TestRepositoryHelmChartsResponse(unittest.TestCase):
    """RepositoryHelmChartsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryHelmChartsResponse(self):
        """Test RepositoryHelmChartsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryHelmChartsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
