"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_time import V1Time
globals()['V1Time'] = V1Time
from openapi_client.model.v1alpha1_application_condition import V1alpha1ApplicationCondition


class TestV1alpha1ApplicationCondition(unittest.TestCase):
    """V1alpha1ApplicationCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationCondition(self):
        """Test V1alpha1ApplicationCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
