"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_ksonnet_parameter import V1alpha1KsonnetParameter
globals()['V1alpha1KsonnetParameter'] = V1alpha1KsonnetParameter
from argocd_python_client.model.v1alpha1_application_source_ksonnet import V1alpha1ApplicationSourceKsonnet


class TestV1alpha1ApplicationSourceKsonnet(unittest.TestCase):
    """V1alpha1ApplicationSourceKsonnet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourceKsonnet(self):
        """Test V1alpha1ApplicationSourceKsonnet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSourceKsonnet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
