"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_orphaned_resource_key import V1alpha1OrphanedResourceKey
globals()['V1alpha1OrphanedResourceKey'] = V1alpha1OrphanedResourceKey
from openapi_client.model.v1alpha1_orphaned_resources_monitor_settings import V1alpha1OrphanedResourcesMonitorSettings


class TestV1alpha1OrphanedResourcesMonitorSettings(unittest.TestCase):
    """V1alpha1OrphanedResourcesMonitorSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1OrphanedResourcesMonitorSettings(self):
        """Test V1alpha1OrphanedResourcesMonitorSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1OrphanedResourcesMonitorSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
