"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_list_meta import V1ListMeta
from openapi_client.model.v1alpha1_app_project import V1alpha1AppProject
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1AppProject'] = V1alpha1AppProject
from openapi_client.model.v1alpha1_app_project_list import V1alpha1AppProjectList


class TestV1alpha1AppProjectList(unittest.TestCase):
    """V1alpha1AppProjectList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1AppProjectList(self):
        """Test V1alpha1AppProjectList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1AppProjectList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
