"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cluster_connector import ClusterConnector
globals()['ClusterConnector'] = ClusterConnector
from openapi_client.model.cluster_dex_config import ClusterDexConfig


class TestClusterDexConfig(unittest.TestCase):
    """ClusterDexConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterDexConfig(self):
        """Test ClusterDexConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterDexConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
