"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_port_status import V1PortStatus
globals()['V1PortStatus'] = V1PortStatus
from openapi_client.model.v1_load_balancer_ingress import V1LoadBalancerIngress


class TestV1LoadBalancerIngress(unittest.TestCase):
    """V1LoadBalancerIngress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1LoadBalancerIngress(self):
        """Test V1LoadBalancerIngress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1LoadBalancerIngress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
