"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_compared_to import V1alpha1ComparedTo
globals()['V1alpha1ComparedTo'] = V1alpha1ComparedTo
from argocd_python_client.model.v1alpha1_sync_status import V1alpha1SyncStatus


class TestV1alpha1SyncStatus(unittest.TestCase):
    """V1alpha1SyncStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncStatus(self):
        """Test V1alpha1SyncStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1SyncStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
