"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.applicationv1alpha1_env_entry import Applicationv1alpha1EnvEntry
globals()['Applicationv1alpha1EnvEntry'] = Applicationv1alpha1EnvEntry
from openapi_client.model.v1alpha1_application_source_plugin import V1alpha1ApplicationSourcePlugin


class TestV1alpha1ApplicationSourcePlugin(unittest.TestCase):
    """V1alpha1ApplicationSourcePlugin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourcePlugin(self):
        """Test V1alpha1ApplicationSourcePlugin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSourcePlugin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
