"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.application_application_rollback_request import ApplicationApplicationRollbackRequest


class TestApplicationApplicationRollbackRequest(unittest.TestCase):
    """ApplicationApplicationRollbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationApplicationRollbackRequest(self):
        """Test ApplicationApplicationRollbackRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationApplicationRollbackRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
