"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_list_meta import V1ListMeta
from argocd_python_client.model.v1alpha1_repository_certificate import V1alpha1RepositoryCertificate
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1RepositoryCertificate'] = V1alpha1RepositoryCertificate
from argocd_python_client.model.v1alpha1_repository_certificate_list import V1alpha1RepositoryCertificateList


class TestV1alpha1RepositoryCertificateList(unittest.TestCase):
    """V1alpha1RepositoryCertificateList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RepositoryCertificateList(self):
        """Test V1alpha1RepositoryCertificateList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1RepositoryCertificateList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
