"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_host_info import V1alpha1HostInfo
from openapi_client.model.v1alpha1_resource_node import V1alpha1ResourceNode
globals()['V1alpha1HostInfo'] = V1alpha1HostInfo
globals()['V1alpha1ResourceNode'] = V1alpha1ResourceNode
from openapi_client.model.v1alpha1_application_tree import V1alpha1ApplicationTree


class TestV1alpha1ApplicationTree(unittest.TestCase):
    """V1alpha1ApplicationTree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationTree(self):
        """Test V1alpha1ApplicationTree"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationTree()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
