"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_resource_action import V1alpha1ResourceAction
globals()['V1alpha1ResourceAction'] = V1alpha1ResourceAction
from openapi_client.model.application_resource_actions_list_response import ApplicationResourceActionsListResponse


class TestApplicationResourceActionsListResponse(unittest.TestCase):
    """ApplicationResourceActionsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationResourceActionsListResponse(self):
        """Test ApplicationResourceActionsListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApplicationResourceActionsListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
