"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_sync_window import V1alpha1SyncWindow


class TestV1alpha1SyncWindow(unittest.TestCase):
    """V1alpha1SyncWindow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncWindow(self):
        """Test V1alpha1SyncWindow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1SyncWindow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
