"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cluster_dex_config import ClusterDexConfig
from openapi_client.model.cluster_google_analytics_config import ClusterGoogleAnalyticsConfig
from openapi_client.model.cluster_help import ClusterHelp
from openapi_client.model.cluster_oidc_config import ClusterOIDCConfig
from openapi_client.model.cluster_plugin import ClusterPlugin
from openapi_client.model.v1alpha1_config_management_plugin import V1alpha1ConfigManagementPlugin
from openapi_client.model.v1alpha1_kustomize_options import V1alpha1KustomizeOptions
from openapi_client.model.v1alpha1_resource_override import V1alpha1ResourceOverride
globals()['ClusterDexConfig'] = ClusterDexConfig
globals()['ClusterGoogleAnalyticsConfig'] = ClusterGoogleAnalyticsConfig
globals()['ClusterHelp'] = ClusterHelp
globals()['ClusterOIDCConfig'] = ClusterOIDCConfig
globals()['ClusterPlugin'] = ClusterPlugin
globals()['V1alpha1ConfigManagementPlugin'] = V1alpha1ConfigManagementPlugin
globals()['V1alpha1KustomizeOptions'] = V1alpha1KustomizeOptions
globals()['V1alpha1ResourceOverride'] = V1alpha1ResourceOverride
from openapi_client.model.cluster_settings import ClusterSettings


class TestClusterSettings(unittest.TestCase):
    """ClusterSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterSettings(self):
        """Test ClusterSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
