"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_health_status import V1alpha1HealthStatus
globals()['V1alpha1HealthStatus'] = V1alpha1HealthStatus
from openapi_client.model.v1alpha1_resource_status import V1alpha1ResourceStatus


class TestV1alpha1ResourceStatus(unittest.TestCase):
    """V1alpha1ResourceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceStatus(self):
        """Test V1alpha1ResourceStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
