"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_fields_v1 import V1FieldsV1


class TestV1FieldsV1(unittest.TestCase):
    """V1FieldsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1FieldsV1(self):
        """Test V1FieldsV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1FieldsV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
