"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_node_system_info import V1NodeSystemInfo


class TestV1NodeSystemInfo(unittest.TestCase):
    """V1NodeSystemInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1NodeSystemInfo(self):
        """Test V1NodeSystemInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1NodeSystemInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
