"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_owner_reference import V1OwnerReference


class TestV1OwnerReference(unittest.TestCase):
    """V1OwnerReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1OwnerReference(self):
        """Test V1OwnerReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1OwnerReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
