"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_load_balancer_ingress import V1LoadBalancerIngress
from openapi_client.model.v1alpha1_resource_ref import V1alpha1ResourceRef
globals()['V1LoadBalancerIngress'] = V1LoadBalancerIngress
globals()['V1alpha1ResourceRef'] = V1alpha1ResourceRef
from openapi_client.model.v1alpha1_resource_networking_info import V1alpha1ResourceNetworkingInfo


class TestV1alpha1ResourceNetworkingInfo(unittest.TestCase):
    """V1alpha1ResourceNetworkingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceNetworkingInfo(self):
        """Test V1alpha1ResourceNetworkingInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceNetworkingInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
