"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_managed_fields_entry import V1ManagedFieldsEntry
from openapi_client.model.v1_owner_reference import V1OwnerReference
from openapi_client.model.v1_time import V1Time
globals()['V1ManagedFieldsEntry'] = V1ManagedFieldsEntry
globals()['V1OwnerReference'] = V1OwnerReference
globals()['V1Time'] = V1Time
from openapi_client.model.v1_object_meta import V1ObjectMeta


class TestV1ObjectMeta(unittest.TestCase):
    """V1ObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ObjectMeta(self):
        """Test V1ObjectMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1ObjectMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
