"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_jwt_tokens import V1alpha1JWTTokens
globals()['V1alpha1JWTTokens'] = V1alpha1JWTTokens
from argocd_python_client.model.v1alpha1_app_project_status import V1alpha1AppProjectStatus


class TestV1alpha1AppProjectStatus(unittest.TestCase):
    """V1alpha1AppProjectStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1AppProjectStatus(self):
        """Test V1alpha1AppProjectStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1AppProjectStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
