"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.project_project_token_create_request import ProjectProjectTokenCreateRequest


class TestProjectProjectTokenCreateRequest(unittest.TestCase):
    """ProjectProjectTokenCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectTokenCreateRequest(self):
        """Test ProjectProjectTokenCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectTokenCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
