"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.certificate_service_api import CertificateServiceApi  # noqa: E501


class TestCertificateServiceApi(unittest.TestCase):
    """CertificateServiceApi unit test stubs"""

    def setUp(self):
        self.api = CertificateServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_certificate_service_create_certificate(self):
        """Test case for certificate_service_create_certificate

        Creates repository certificates on the server  # noqa: E501
        """
        pass

    def test_certificate_service_delete_certificate(self):
        """Test case for certificate_service_delete_certificate

        Delete the certificates that match the RepositoryCertificateQuery  # noqa: E501
        """
        pass

    def test_certificate_service_list_certificates(self):
        """Test case for certificate_service_list_certificates

        List all available repository certificates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
