"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_application_destination import V1alpha1ApplicationDestination
from openapi_client.model.v1alpha1_application_source import V1alpha1ApplicationSource
from openapi_client.model.v1alpha1_info import V1alpha1Info
from openapi_client.model.v1alpha1_resource_ignore_differences import V1alpha1ResourceIgnoreDifferences
from openapi_client.model.v1alpha1_sync_policy import V1alpha1SyncPolicy
globals()['V1alpha1ApplicationDestination'] = V1alpha1ApplicationDestination
globals()['V1alpha1ApplicationSource'] = V1alpha1ApplicationSource
globals()['V1alpha1Info'] = V1alpha1Info
globals()['V1alpha1ResourceIgnoreDifferences'] = V1alpha1ResourceIgnoreDifferences
globals()['V1alpha1SyncPolicy'] = V1alpha1SyncPolicy
from openapi_client.model.v1alpha1_application_spec import V1alpha1ApplicationSpec


class TestV1alpha1ApplicationSpec(unittest.TestCase):
    """V1alpha1ApplicationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSpec(self):
        """Test V1alpha1ApplicationSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
