"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1alpha1_application_destination import V1alpha1ApplicationDestination


class TestV1alpha1ApplicationDestination(unittest.TestCase):
    """V1alpha1ApplicationDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationDestination(self):
        """Test V1alpha1ApplicationDestination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationDestination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
