"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1_list_meta import V1ListMeta
from argocd_python_client.model.v1alpha1_repo_creds import V1alpha1RepoCreds
globals()['V1ListMeta'] = V1ListMeta
globals()['V1alpha1RepoCreds'] = V1alpha1RepoCreds
from argocd_python_client.model.v1alpha1_repo_creds_list import V1alpha1RepoCredsList


class TestV1alpha1RepoCredsList(unittest.TestCase):
    """V1alpha1RepoCredsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1RepoCredsList(self):
        """Test V1alpha1RepoCredsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1RepoCredsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
