"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_command import V1alpha1Command


class TestV1alpha1Command(unittest.TestCase):
    """V1alpha1Command unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1Command(self):
        """Test V1alpha1Command"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1Command()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
