"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.repository_app_info import RepositoryAppInfo


class TestRepositoryAppInfo(unittest.TestCase):
    """RepositoryAppInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryAppInfo(self):
        """Test RepositoryAppInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RepositoryAppInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
