"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_helm_file_parameter import V1alpha1HelmFileParameter
from argocd_python_client.model.v1alpha1_helm_parameter import V1alpha1HelmParameter
globals()['V1alpha1HelmFileParameter'] = V1alpha1HelmFileParameter
globals()['V1alpha1HelmParameter'] = V1alpha1HelmParameter
from argocd_python_client.model.v1alpha1_application_source_helm import V1alpha1ApplicationSourceHelm


class TestV1alpha1ApplicationSourceHelm(unittest.TestCase):
    """V1alpha1ApplicationSourceHelm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourceHelm(self):
        """Test V1alpha1ApplicationSourceHelm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ApplicationSourceHelm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
