"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_node_system_info import V1NodeSystemInfo
from openapi_client.model.v1alpha1_host_resource_info import V1alpha1HostResourceInfo
globals()['V1NodeSystemInfo'] = V1NodeSystemInfo
globals()['V1alpha1HostResourceInfo'] = V1alpha1HostResourceInfo
from openapi_client.model.v1alpha1_host_info import V1alpha1HostInfo


class TestV1alpha1HostInfo(unittest.TestCase):
    """V1alpha1HostInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1HostInfo(self):
        """Test V1alpha1HostInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1HostInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
