"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cluster_plugin import ClusterPlugin


class TestClusterPlugin(unittest.TestCase):
    """ClusterPlugin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterPlugin(self):
        """Test ClusterPlugin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClusterPlugin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
