"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_application_destination import V1alpha1ApplicationDestination
from argocd_python_client.model.v1alpha1_application_source import V1alpha1ApplicationSource
globals()['V1alpha1ApplicationDestination'] = V1alpha1ApplicationDestination
globals()['V1alpha1ApplicationSource'] = V1alpha1ApplicationSource
from argocd_python_client.model.v1alpha1_compared_to import V1alpha1ComparedTo


class TestV1alpha1ComparedTo(unittest.TestCase):
    """V1alpha1ComparedTo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ComparedTo(self):
        """Test V1alpha1ComparedTo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ComparedTo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
