"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.project_service_api import ProjectServiceApi  # noqa: E501


class TestProjectServiceApi(unittest.TestCase):
    """ProjectServiceApi unit test stubs"""

    def setUp(self):
        self.api = ProjectServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_project_service_create(self):
        """Test case for project_service_create

        Create a new project  # noqa: E501
        """
        pass

    def test_project_service_create_token(self):
        """Test case for project_service_create_token

        Create a new project token  # noqa: E501
        """
        pass

    def test_project_service_delete(self):
        """Test case for project_service_delete

        Delete deletes a project  # noqa: E501
        """
        pass

    def test_project_service_delete_token(self):
        """Test case for project_service_delete_token

        Delete a new project token  # noqa: E501
        """
        pass

    def test_project_service_get(self):
        """Test case for project_service_get

        Get returns a project by name  # noqa: E501
        """
        pass

    def test_project_service_get_global_projects(self):
        """Test case for project_service_get_global_projects

        Get returns a virtual project by name  # noqa: E501
        """
        pass

    def test_project_service_get_sync_windows_state(self):
        """Test case for project_service_get_sync_windows_state

        GetSchedulesState returns true if there are any active sync syncWindows  # noqa: E501
        """
        pass

    def test_project_service_list(self):
        """Test case for project_service_list

        List returns list of projects  # noqa: E501
        """
        pass

    def test_project_service_list_events(self):
        """Test case for project_service_list_events

        ListEvents returns a list of project events  # noqa: E501
        """
        pass

    def test_project_service_update(self):
        """Test case for project_service_update

        Update updates a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
