"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.project_project_token_response import ProjectProjectTokenResponse


class TestProjectProjectTokenResponse(unittest.TestCase):
    """ProjectProjectTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectTokenResponse(self):
        """Test ProjectProjectTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectProjectTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
