"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.v1_time import V1Time
from openapi_client.model.v1alpha1_health_status import V1alpha1HealthStatus
from openapi_client.model.v1alpha1_info_item import V1alpha1InfoItem
from openapi_client.model.v1alpha1_resource_networking_info import V1alpha1ResourceNetworkingInfo
from openapi_client.model.v1alpha1_resource_ref import V1alpha1ResourceRef
globals()['V1Time'] = V1Time
globals()['V1alpha1HealthStatus'] = V1alpha1HealthStatus
globals()['V1alpha1InfoItem'] = V1alpha1InfoItem
globals()['V1alpha1ResourceNetworkingInfo'] = V1alpha1ResourceNetworkingInfo
globals()['V1alpha1ResourceRef'] = V1alpha1ResourceRef
from openapi_client.model.v1alpha1_resource_node import V1alpha1ResourceNode


class TestV1alpha1ResourceNode(unittest.TestCase):
    """V1alpha1ResourceNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceNode(self):
        """Test V1alpha1ResourceNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ResourceNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
