"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.session_get_user_info_response import SessionGetUserInfoResponse


class TestSessionGetUserInfoResponse(unittest.TestCase):
    """SessionGetUserInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionGetUserInfoResponse(self):
        """Test SessionGetUserInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SessionGetUserInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
