"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import argocd_python_client
from argocd_python_client.model.v1alpha1_jwt_token import V1alpha1JWTToken
globals()['V1alpha1JWTToken'] = V1alpha1JWTToken
from argocd_python_client.model.v1alpha1_project_role import V1alpha1ProjectRole


class TestV1alpha1ProjectRole(unittest.TestCase):
    """V1alpha1ProjectRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ProjectRole(self):
        """Test V1alpha1ProjectRole"""
        # FIXME: construct object with mandatory attributes with example values
        # model = V1alpha1ProjectRole()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
