"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.gpg_key_service_api import GPGKeyServiceApi  # noqa: E501


class TestGPGKeyServiceApi(unittest.TestCase):
    """GPGKeyServiceApi unit test stubs"""

    def setUp(self):
        self.api = GPGKeyServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_g_pg_key_service_create(self):
        """Test case for g_pg_key_service_create

        Create one or more GPG public keys in the server's configuration  # noqa: E501
        """
        pass

    def test_g_pg_key_service_delete(self):
        """Test case for g_pg_key_service_delete

        Delete specified GPG public key from the server's configuration  # noqa: E501
        """
        pass

    def test_g_pg_key_service_get(self):
        """Test case for g_pg_key_service_get

        Get information about specified GPG public key from the server  # noqa: E501
        """
        pass

    def test_g_pg_key_service_list(self):
        """Test case for g_pg_key_service_list

        List all available repository certificates  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
