# flake8: noqa

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.1"

# import ApiClient
from argocd_python_client.api_client import ApiClient

# import Configuration
from argocd_python_client.configuration import Configuration

# import exceptions
from argocd_python_client.exceptions import OpenApiException
from argocd_python_client.exceptions import ApiAttributeError
from argocd_python_client.exceptions import ApiTypeError
from argocd_python_client.exceptions import ApiValueError
from argocd_python_client.exceptions import ApiKeyError
from argocd_python_client.exceptions import ApiException
