"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from argocd_python_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from argocd_python_client.exceptions import ApiAttributeError


def lazy_import():
    from argocd_python_client.model.v1_group_kind import V1GroupKind
    from argocd_python_client.model.v1alpha1_application_destination import V1alpha1ApplicationDestination
    from argocd_python_client.model.v1alpha1_orphaned_resources_monitor_settings import V1alpha1OrphanedResourcesMonitorSettings
    from argocd_python_client.model.v1alpha1_project_role import V1alpha1ProjectRole
    from argocd_python_client.model.v1alpha1_signature_key import V1alpha1SignatureKey
    from argocd_python_client.model.v1alpha1_sync_window import V1alpha1SyncWindow
    globals()['V1GroupKind'] = V1GroupKind
    globals()['V1alpha1ApplicationDestination'] = V1alpha1ApplicationDestination
    globals()['V1alpha1OrphanedResourcesMonitorSettings'] = V1alpha1OrphanedResourcesMonitorSettings
    globals()['V1alpha1ProjectRole'] = V1alpha1ProjectRole
    globals()['V1alpha1SignatureKey'] = V1alpha1SignatureKey
    globals()['V1alpha1SyncWindow'] = V1alpha1SyncWindow


class V1alpha1AppProjectSpec(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'cluster_resource_blacklist': ([V1GroupKind],),  # noqa: E501
            'cluster_resource_whitelist': ([V1GroupKind],),  # noqa: E501
            'description': (str,),  # noqa: E501
            'destinations': ([V1alpha1ApplicationDestination],),  # noqa: E501
            'namespace_resource_blacklist': ([V1GroupKind],),  # noqa: E501
            'namespace_resource_whitelist': ([V1GroupKind],),  # noqa: E501
            'orphaned_resources': (V1alpha1OrphanedResourcesMonitorSettings,),  # noqa: E501
            'roles': ([V1alpha1ProjectRole],),  # noqa: E501
            'signature_keys': ([V1alpha1SignatureKey],),  # noqa: E501
            'source_repos': ([str],),  # noqa: E501
            'sync_windows': ([V1alpha1SyncWindow],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'cluster_resource_blacklist': 'clusterResourceBlacklist',  # noqa: E501
        'cluster_resource_whitelist': 'clusterResourceWhitelist',  # noqa: E501
        'description': 'description',  # noqa: E501
        'destinations': 'destinations',  # noqa: E501
        'namespace_resource_blacklist': 'namespaceResourceBlacklist',  # noqa: E501
        'namespace_resource_whitelist': 'namespaceResourceWhitelist',  # noqa: E501
        'orphaned_resources': 'orphanedResources',  # noqa: E501
        'roles': 'roles',  # noqa: E501
        'signature_keys': 'signatureKeys',  # noqa: E501
        'source_repos': 'sourceRepos',  # noqa: E501
        'sync_windows': 'syncWindows',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """V1alpha1AppProjectSpec - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            cluster_resource_blacklist ([V1GroupKind]): [optional]  # noqa: E501
            cluster_resource_whitelist ([V1GroupKind]): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            destinations ([V1alpha1ApplicationDestination]): [optional]  # noqa: E501
            namespace_resource_blacklist ([V1GroupKind]): [optional]  # noqa: E501
            namespace_resource_whitelist ([V1GroupKind]): [optional]  # noqa: E501
            orphaned_resources (V1alpha1OrphanedResourcesMonitorSettings): [optional]  # noqa: E501
            roles ([V1alpha1ProjectRole]): [optional]  # noqa: E501
            signature_keys ([V1alpha1SignatureKey]): [optional]  # noqa: E501
            source_repos ([str]): [optional]  # noqa: E501
            sync_windows ([V1alpha1SyncWindow]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """V1alpha1AppProjectSpec - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            cluster_resource_blacklist ([V1GroupKind]): [optional]  # noqa: E501
            cluster_resource_whitelist ([V1GroupKind]): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            destinations ([V1alpha1ApplicationDestination]): [optional]  # noqa: E501
            namespace_resource_blacklist ([V1GroupKind]): [optional]  # noqa: E501
            namespace_resource_whitelist ([V1GroupKind]): [optional]  # noqa: E501
            orphaned_resources (V1alpha1OrphanedResourcesMonitorSettings): [optional]  # noqa: E501
            roles ([V1alpha1ProjectRole]): [optional]  # noqa: E501
            signature_keys ([V1alpha1SignatureKey]): [optional]  # noqa: E501
            source_repos ([str]): [optional]  # noqa: E501
            sync_windows ([V1alpha1SyncWindow]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
